config/routes.rb
Rails.application.routes.draw do
  resources :tweets
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "tweets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    include PgSearch::Model

    pg_search_scope :search_full_text, against:{
        UserName: 'A',
        id: 'B',
    },

    using: {
        tsearch: {
            prefix: true, 
            any_word: true,
            dictionary: "spanish"
        }
    }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    Pagy::DEFAULT[:items] = 10
    include Pagy::Backend

    require 'pagy/extras/bootstrap'
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy]

  # GET /tweets or /tweets.json
  def index
    @pagy, @tweets = pagy(Tweet.all)
    if params[:query_text].present?
      @pagy, @tweets = pagy(Tweet.search_full_text(params[:query_text]))
    end
  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweet_url(@tweet), notice: "El Tweet fue creado exitosamente" }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to tweet_url(@tweet), notice: "El Tweet fue actualizado correctamente" }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "El Tweet fue eliminado exitosamente." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:descrption, :UserName)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CloneTwitterFOV</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
   
  </body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</html>

app/views/tweets/_form.html.erb
<div class="container">
  <%= form_with(model: tweet) do |form| %>
  <% if tweet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<form>
  <div class="form-group mb-3">
    <%= form.label :UserName, style: "display: block" %>
    <%= form.text_field :UserName, class: "form-control"%>
  </div>

  <div class="form-group mb-3">
    <%= form.label :descrption, style: "display: block" %>
    <%= form.text_area :descrption, class: "form-control"%>
  </div>

  <div class="form-group">
    <%= form.submit "Twittear", class: "btn btn-success" %>
  </div>
</form>
  
<% end %>

</div>

app/views/tweets/_tweet.html.erb
<div id="<%= dom_id tweet %>">
  <div class="container">
    <p>
      <strong><%= tweet.UserName %></strong>
    </p>
  </div>
  
  <div class="container">
    <p>
      <%= tweet.descrption %>
    </p>
  </div>
  

</div>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Ver más sobre éste tweet", @tweet, class: "btn btn-info"  %> |
  <%= link_to "Volver al Inicio", tweets_path, class: "btn btn-primary"%>
</div>

app/views/tweets/index.html.erb
<div class="row mt-5">
  <div class="col-md-3">
    <div class="container mb-5">
      <h2><i class="fa-brands fa-twitter fa-2xl" style="color:black;"></i> 
    </div>
    <div class="container">
      <%= link_to "Realizar un Nuevo Tweet", new_tweet_path, class: "btn btn-success" %>
    </div>  
  </div>

  <div class="col-md-5 mt-5">
    <div class="container mb-5">
      <h1>Inicio</h1>
    </div>
    <div class="container justify-content-center">
      <%=raw pagy_bootstrap_nav(@pagy)%>
    </div>
    <div id="tweets">
      <% @tweets.each do |tweet| %>
        <div class="card border-secondary">
          <div class="card-body">
            <%= render tweet %>
            <p>
              <%= link_to "Mostrar Este Tweet", tweet, class: "btn btn-info" %>
            </p>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="col-md-4">
    <%= form_with url: tweets_path, method: :get, html: { class: "form-inline" } do |form|%>
      <div class="input-group">
        <%= form.text_field :query_text, value: params[:query_text], class: "form-control" %>
        <div class="input-group-append">
          <%= form.submit "Buscar Tweet", class: "btn btn-info" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/tweets/new.html.erb
<h1>Nuevo Tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Volver al Inicio", tweets_path, class: "btn btn-primary" %>
</div>

app/views/tweets/show.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>
  <div class="card border-secondary">
    <div class="card-body"></div>
      <%= render @tweet %>
      <div class=" container d-flex justify-content-start mt-2 mb-1">
        <p>
          <%= link_to "Editar este Tweet", edit_tweet_path(@tweet), class: "btn btn-success"%>
        </p>
         <%= button_to "Eliminar este Tweet", @tweet, method: :delete, class: "btn btn-danger" %>
      </div>  
    </div>
  </div>
  
  
  <div class="container mt-3">
    <%= link_to "Volver al Inicio", tweets_path, class: "btn btn-primary" %>
  </div>

</div>